version: "3"

services:
  development:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4300:4300
    volumes:
      - ..:/workspace
      - /workspace/Frontend/node_modules
